FROM io2060/vision-liveness-detector-build:manylinux_2_28_x86_64

ARG RELEASE_VERSION="0.0.1-dev.0"

# Set the environment variable for your Python binary (optional)
ENV PYTHON_BIN=/opt/python/cp312-cp312/bin/python3.12

# Prepend the Python directory to the PATH for all following layers/commands
ENV PATH="/opt/python/cp312-cp312/bin:${PATH}"

RUN cd build/mediapipe/ && bazel build -c opt --linkopt -s --strip always --define MEDIAPIPE_DISABLE_GPU=1 livenessDetectorServerApp:livenessDetectorServer
RUN cp audit_livenessDetectorServerApp.sh ./build/mediapipe/bazel-bin/livenessDetectorServerApp/
RUN cd build/mediapipe/bazel-bin/livenessDetectorServerApp/ && \
    ./audit_livenessDetectorServerApp.sh

RUN mkdir -p ./wrappers/python/liveness_detector/server
RUN cp build/mediapipe/bazel-bin/livenessDetectorServerApp/livenessDetectorServer ./wrappers/python/liveness_detector/server/
RUN cp -R build/mediapipe/bazel-bin/livenessDetectorServerApp/lib ./wrappers/python/liveness_detector/server/lib

RUN cp -R src/livenessDetectorServerApp/gestures ./wrappers/python/liveness_detector
#RUN cp -R src/livenessDetector/*.json ../../wrappers/python/liveness_detector

RUN $PYTHON_BIN -m pip install --upgrade pip setuptools
RUN $PYTHON_BIN -m pip install wheel auditwheel
RUN ln -sf $PYTHON_BIN /usr/bin/python && \
    ln -sf $PYTHON_BIN /usr/bin/python3

RUN cd ./wrappers/python && RELEASE_VERSION=${RELEASE_VERSION} $PYTHON_BIN setup.py bdist_wheel --python-tag=py3 --plat-name=manylinux2014_x86_64

